// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/weather.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeatherSericeClient is the client API for WeatherSerice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherSericeClient interface {
	GetWeather(ctx context.Context, in *GetWeatherRequest, opts ...grpc.CallOption) (*GetWeatherResponse, error)
}

type weatherSericeClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherSericeClient(cc grpc.ClientConnInterface) WeatherSericeClient {
	return &weatherSericeClient{cc}
}

func (c *weatherSericeClient) GetWeather(ctx context.Context, in *GetWeatherRequest, opts ...grpc.CallOption) (*GetWeatherResponse, error) {
	out := new(GetWeatherResponse)
	err := c.cc.Invoke(ctx, "/proto.WeatherSerice/GetWeather", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherSericeServer is the server API for WeatherSerice service.
// All implementations must embed UnimplementedWeatherSericeServer
// for forward compatibility
type WeatherSericeServer interface {
	GetWeather(context.Context, *GetWeatherRequest) (*GetWeatherResponse, error)
	mustEmbedUnimplementedWeatherSericeServer()
}

// UnimplementedWeatherSericeServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherSericeServer struct {
}

func (UnimplementedWeatherSericeServer) GetWeather(context.Context, *GetWeatherRequest) (*GetWeatherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeather not implemented")
}
func (UnimplementedWeatherSericeServer) mustEmbedUnimplementedWeatherSericeServer() {}

// UnsafeWeatherSericeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherSericeServer will
// result in compilation errors.
type UnsafeWeatherSericeServer interface {
	mustEmbedUnimplementedWeatherSericeServer()
}

func RegisterWeatherSericeServer(s grpc.ServiceRegistrar, srv WeatherSericeServer) {
	s.RegisterService(&WeatherSerice_ServiceDesc, srv)
}

func _WeatherSerice_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherSericeServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WeatherSerice/GetWeather",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherSericeServer).GetWeather(ctx, req.(*GetWeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherSerice_ServiceDesc is the grpc.ServiceDesc for WeatherSerice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherSerice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WeatherSerice",
	HandlerType: (*WeatherSericeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeather",
			Handler:    _WeatherSerice_GetWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/weather.proto",
}
